apiVersion: v1
kind: Pod
metadata:
  name: secure-busybox
spec:
  securityContext:
    runAsUser: 1000
  containers:
    - name: secure-busybox
      image: busybox:1.34
      command: [ "sh", "-c", "sleep 1h" ]
