apiVersion: v1
kind: Pod
metadata:
  name: mongo-volume
spec:
  volumes:
    - name: host-volume
      hostPath:
        path: /mongo-data
        type: DirectoryOrCreate
  containers:
    - name: mongo-volume
      image: mongo:latest
      volumeMounts:
        - mountPath: /data/db
          name: host-volume
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
